repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.5
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/pycqa/isort
  rev: 6.0.0
  hooks:
  - id: isort
    args: [--profile, black, --force-sort-within-sections, --skip-glob, '*__init__.py']
